### ISSUE TITLE
Links in pg-pages contains bad links (results in 404)

### ISSUE THREAD

**Issue by joakime** [eclipse-ee4j/javamail#390]
**Describe the bug**
The `README.md` in your `gh-pages` branch has many URLs that result in 404 responses.

https://github.com/eclipse-ee4j/javamail/blob/gh-pages/README.md

Examples:

``` markdown
|[jakarta.mail.jar](https://github.com/eclipse-ee4j/mail/releases/download/1.6.3/jakarta.mail.jar)|The Jakarta Mail implementation, including the SMTP, IMAP, and POP3 protocol providers|
...
The Jakarta Mail API documentation is available
[here](https://eclipse-ee4j.github.io/mail/docs/api/)
...
and the Jakarta Mail specification is available
[here](https://javaee.github.io/mail/docs/mail-spec-1.6.pdf).
...
Some sample programs showing how to use the Jakarta Mail APIs are available
[here](https://github.com/eclipse-ee4j/mail/releases/download/1.6.3/javamail-samples.zip).
...
Jakarta Mail bugs are tracked in the
[GitHub Jakarta Mail project issue tracker](https://github.com/eclipse-ee4j/mail/issues).
...
in the [Releases](https://github.com/eclipse-ee4j/mail/releases) area of
this project.
```

The `_config.yml` also has a few bad links

https://github.com/eclipse-ee4j/javamail/blob/gh-pages/_config.yml

Examples:

``` yaml
  source: https://github.com/eclipse-ee4j/mail
...
  download: https://github.com/eclipse-ee4j/mail/releases
  mailinglist: https://accounts.eclipse.org/mailing-list/mail-dev
```

This kinds looks like the result of an overzealous search/replace.
